version: '2'
services:
  tom-api:
    build: ./express
    ports:
     - "8123:8123"
    depends_on:
     - tom-mysql
    environment:
     - DATABASE_HOST=127.0.0.1
    volumes:
     - ./express/api:/app/api
  tom-mysql:
    build: ./database
    ports:
     - "3306:3306"
