version: '2'
services:
  api:
    container_name: 'tom_api'
    build: ./express
    ports:
     - "8080:8080"
    depends_on:
     - mysql
    volumes:
     - ./express/api:/app/api
  mysql:
    container_name: 'tom_mysql'
    build: ./database
    restart: always
    ports:
     - "3306:3306"
