version: '2'
services:
  api:
    build: ./express
    ports:
     - "8080:8080"
    depends_on:
     - mysql
    environment:
     - DATABASE_HOST=127.0.0.1
    volumes:
     - ./express/api:/app/api
  mysql:
    build: ./database
    restart: always
    ports:
     - "3306:3306"
